<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=.0">
    <title>Document</title>
</head>
<body>
<html><body>
 

 <option id='swift Swim		Boosts the Pokémons Speed in rain.	'>Swift Swim</option>
 <option id='sturdy		It cannot be knocked out with one hit.	'>Sturdy</option>
 <option id='Keen Eye		Prevents other Pokémon from lowering accuracy.	'>Keen Eye</option>
 <option id='Levitate		Gives immunity to Ground type moves.	'>Levitate</option>
 <option id='Intimidate		Lowers the foes Attack stat.	'>Intimidate</option>
 <option id='Inner Focus		The Pokémon is protected from flinching.	'>Inner Focus</option>
 <option id='Chlorophyll		Boosts the Pokémons Speed in sunshine.	'>Chlorophyll</option>
 <option id='Pressure		The Pokémon raises the foes PP usage.	'>Pressure</option>
 <option id='Gluttony		Encourages the early use of a held Berry.	'>Gluttony</option>
 <option id='Frisk		The Pokémon can check a foes held item.	'>Frisk	</option>
 <option id='sheer Force		Removes added effects to increase move damage.	'>Sheer Force</option>
 <option id='swarm	9	Powers up Bug-type moves in a pinch.	'>Swarm</option>
 <option id='Run Away	9	Enables a sure getaway from wild Pokémon.	'>Run Away</option>
 <option id='Torrent		Powers up Water-type moves in a pinch.	'>Torrent</option>
 <option id='Own Tempo		Prevents the Pokémon from becoming confused.	'>Own Tempo</option>
 <option id='Overgrow		Powers up Grass-type moves in a pinch.	'>Overgrow</option>
 <option id='Blaze		Powers up Fire-type moves in a pinch.	'>Blaze</option>
 <option id='shell Armor		The Pokémon is protected against critical hits.	'>Shell Armor</option>
 <option id='Pickup		The Pokémon may pick up items.	'>Pickup</option>
 <option id='Overcoat		Protects the Pokémon from weather damage.	'>Overcoat</option>
 <option id='Flash Fire		It powers up Fire-type moves if its hit by one.	'>Flash Fire</option>
 <option id='Water Absorb		Restores HP if hit by a Water-type move.	'>Water Absorb</option>
 <option id='Unnerve		Makes the foe nervous and unable to eat Berries.	'>Unnerve	</option>
 <option id='Thick Fat		Ups resistance to Fire- and Ice-type moves.	'>Thick Fat	</option>
 <option id='Telepathy		Anticipates an allys attack and dodges it.	'>Telepathy</option>
 <option id='sand Veil		Boosts the Pokémons evasion in a sandstorm.	'>Sand Veil</option>
 <option id='Regenerator		Restores a little HP when withdrawn from battle.	'>Regenerator</option>
 <option id='Oblivious		Prevents it from becoming infatuated.	'>Oblivious</option>
 <option id='Infiltrator		Passes through the foes barrier and strikes.	'>Infiltrator</option>
 <option id='Hustle		Boosts the Attack stat, but lowers accuracy.	'>Hustle</option>
 <option id='Guts		Boosts Attack if there is a status problem.	'>Guts</option>
 <option id='Weak Armor		Physical attacks lower Defense and raise Speed.	'>Weak Armor	</option>
 <option id='Technician		Powers up the Pokémons weaker moves.	'>Technician</option>
 <option id='Hydration		Heals status problems if it is raining.	'>Hydration	</option>
 <option id='static		Contact with the Pokémon may cause paralysis.	'>Static</option>
 <option id='shed Skin		The Pokémon may heal its own status problems.	'>Shed Skin</option>
 <option id='Rock Head		Protects the Pokémon from recoil damage.	'>Rock Head</option>
 <option id='Mold Breaker		Moves can be used regardless of Abilities.	'>Mold Breaker</option>
 <option id='Leaf Guard		Prevents problems with status in sunny weather.	'>Leaf Guard</option>
 <option id='sap Sipper	0	Boosts Attack when hit by a Grass-type move.	'>Sap Sipper</option>
 <option id='Insomnia	0	Prevents the Pokémon from falling asleep.	'>Insomnia</option>
 <option id='Flame Body	0	Contact with the Pokémon may burn the attacker.	'>Flame Body</option>
 <option id='Rattled	9	Bug, Ghost or Dark type moves scare it and boost its Speed.	'>Rattled	</option>
 <option id='Poison Point	9	Contact with the Pokémon may poison the attacker.	'>Poison Point</option>
 <option id='Lightning Rod	9	Draws in all Electric-type moves to up Sp. Attack.	'>Lightning Rod</option>
 <option id='sand Force		Boosts certain moves power in a sandstorm.	'>Sand Force</option>
 <option id='Rivalry		Deals more damage to a Pokémon of same gender.	'>Rivalry</option>
 <option id='Ice Body		The Pokémon gradually regains HP in a hailstorm.	'>Ice Body</option>
 <option id='Damp		Prevents the use of self-destructing moves.	'>Damp</option>
 <option id='synchronize		Passes a burn, poison, or paralysis to the foe.	'>Synchronize</option>
 <option id='soundproof		Gives immunity to sound-based moves.	'>Soundproof</option>
 <option id='sniper		Powers up moves if they become critical hits.	'>Sniper</option>
 <option id='Prankster		Gives priority to a status move.	'>Prankster	</option>
 <option id='Natural Cure		All status problems heal when it switches out.	'>Natural Cure</option>
 <option id='Defiant		Sharply raises Attack when the Pokémons stats are lowered.	'>Defiant</option>
 <option id='steadfast		Raises Speed each time the Pokémon flinches.	'>Steadfast</option>
 <option id='Early Bird		The Pokémon awakens quickly from sleep.	'>Early Bird</option>
 <option id='Clear Body		Prevents other Pokémon from lowering its stats.	'>Clear Body	</option>
 <option id='Adaptability		Powers up moves of the same type.	'>Adaptability</option>
 <option id='Vital Spirit		Prevents the Pokémon from falling asleep.	'>Vital Spirit	</option>
 <option id='Unburden		Raises Speed if a held item is used.	'>Unburden</option>
 <option id='Iron Fist		Boosts the power of punching moves.	'>Iron Fist	</option>
 <option id='snow Cloak		Raises evasion in a hailstorm.	'>Snow Cloak</option>
 <option id='Limber		The Pokémon is protected from paralysis.	'>Limber</option>
 <option id='Cute Charm		Contact with the Pokémon may cause infatuation.	'>Cute Charm</option>
 <option id='Big Pecks		Protects the Pokémon from Defense-lowering attacks.	'>Big Pecks</option>
 <option id='Anticipation		Senses a foes dangerous moves.	'>Anticipation</option>
 <option id='serene Grace		Boosts the likelihood of added effects appearing.	'>Serene Grace</option>
 <option id='scrappy		Enables moves to hit Ghost-type Pokémon.	'>Scrappy</option>
 <option id='Reckless		Powers up moves that have recoil damage.	'>Reckless</option>
 <option id='Rain Dish		The Pokémon gradually regains HP in rain.	'>Rain Dish</option>
 <option id='Moxie		Boosts Attack after knocking out any Pokémon.	'>Moxie</option>
 <option id='Cursed Body		May disable a move used on the Pokémon.	'>Cursed Body</option>
 <option id='speed Boost		Its Speed stat is gradually boosted.	'>Speed Boost</option>
 <option id='Poison Touch		May poison targets when a Pokémon makes contact.	'>Poison Touch</option>
 <option id='Justified		Raises Attack when hit by a Dark-type move.	'>Justified		</option>
 <option id='Healer		May heal an allys status conditions.	'>Healer</option>
 <option id='Analytic		Boosts move power when the Pokémon moves last.	'>Analytic</option>
 <option id='Water Veil		Prevents the Pokémon from getting a burn.	'>Water Veil</option>
 <option id='strong Jaw		Boosts the power of biting moves.	'>Strong Jaw</option>
 <option id='shield Dust		Blocks the added effects of attacks taken.	'>Shield Dust	</option>
 <option id='Quick Feet		Boosts Speed if there is a status problem.	'>Quick Feet</option>
 <option id='Hyper Cutter		Prevents other Pokémon from lowering Attack stat.	'>Hyper Cutter		</option>
 <option id='Effect Spore		Contact may poison or cause paralysis or sleep.	'>Effect Spore		</option>
 <option id='Compound Eyes		The Pokémons accuracy is boosted.	'>Compound Eyes	</option>
 <option id='Beast Boost		The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.	'>Beast Boost</option>
 <option id='Battle Armor		The Pokémon is protected against critical hits.	'>Battle Armor</option>
 <option id='skill Link	0	Increases the frequency of multi-strike moves.	'>Skill Link</option>
 <option id='Pickpocket	0	Steals an item when hit by another Pokémon.	'>Pickpocket</option>
 <option id='No Guard	0	Ensures attacks by or against the Pokémon land.	'>No Guard</option>
 <option id='Magic Guard	0	Protects the Pokémon from indirect damage.	'>Magic Guard</option>
 <option id='Klutz	0	The Pokémon cant use any held items.	'>Klutz</option>
 <option id='Contrary	0	Makes stat changes have an opposite effect.	'>Contrary</option>
 <option id='Competitive	0	Sharply raises Special Attack when the Pokémons stats are lowered.	'>Competitive</option>
 <option id='Bulletproof	0	Protects the Pokémon from ball and bomb moves.	'>Bulletproof</option>
 <option id='Aftermath	0	Damages the attacker landing the finishing hit.	'>Aftermath</option>
 <option id='Volt Absorb	9	Restores HP if hit by an Electric-type move.	'>Volt Absorb	</option>
 <option id='Unaware	9	Ignores any stat changes in the Pokémon.	'>Unaware		</option>
 <option id='Tinted Lens	9	Powers up “not very effective” moves.	'>Tinted Lens		</option>
 <option id='sweet Veil	9	Prevents the Pokémon and allies from falling asleep.	'>Sweet Veil</option>
 <option id='super Luck	9	Heightens the critical-hit ratios of moves.	'>Super Luck	</option>
 <option id='stench	9	The stench may cause the target to flinch.	'>Stench	</option>
 <option id='solar Power	9	In sunshine, Sp. Atk is boosted but HP decreases.	'>Solar Power	</option>
 <option id='sand Rush	9	Boosts the Pokémons Speed in a sandstorm.	'>Sand Rush</option>
 <option id='Plus	9	Ups Sp. Atk if another Pokémon has Plus or Minus.	'>Plus</option>
 <option id='Magnet Pull	9	Prevents Steel-type Pokémon from escaping.	'>Magnet Pull</option>
 <option id='Magic Bounce	9	Reflects status- changing moves.	'>Magic Bounce</option>
 <option id='Anger Point	9	Maxes Attack after taking a critical hit.	'>Anger Point</option>
 <option id='Tough Claws		Boosts the power of contact moves.	'>Tough Claws</option>
 <option id='Tangled Feet		Raises evasion if the Pokémon is confused.	'>Tangled Feet</option>
 <option id='sticky Hold		Protects the Pokémon from item theft.	'>Sticky Hold</option>
 <option id='snow Warning		The Pokémon summons a hailstorm in battle.	'>Snow Warning</option>
 <option id='Illuminate		Raises the likelihood of meeting wild Pokémon.	'>Illuminate</option>
 <option id='Heavy Metal		Doubles the Pokémons weight.	'>Heavy Metal	</option>
 <option id='Friend Guard		Reduces damage done to allies.	'>Friend Guard	</option>
 <option id='storm Drain		Draws in all Water-type moves to up Sp. Attack.	'>Storm Drain</option>
 <option id='slush Rush		Boosts the Pokémons Speed stat in a hailstorm.	'>Slush Rush</option>
 <option id='Moody		Raises one stat and lowers another.	'>Moody	</option>
 <option id='Minus		Ups Sp. Atk if another Pokémon has Plus or Minus.	'>Minus	</option>
 <option id='Dry Skin		Reduces HP if it is hot. Water restores HP.	'>Dry Skin	</option>
 <option id='Cloud Nine		Eliminates the effects of weather.	'>Cloud Nine	</option>
 <option id='Trace		The Pokémon copies a foes Ability.	'>Trace	</option>
 <option id='shadow Tag		Prevents the foe from escaping.	'>Shadow Tag</option>
 <option id='Rough Skin		Inflicts damage to the attacker on contact.	'>Rough Skin</option>
 <option id='Magician		The Pokémon steals the held item of a Pokémon it hits with a move.	'>Magician	</option>
 <option id='Light Metal		Halves the Pokémons weight.	'>Light Metal		</option>
 <option id='Huge Power		Raises the Pokémons Attack stat.	'>Huge Power	</option>
 <option id='Harvest		May create another Berry after one is used.	'>Harvest</option>
 <option id='Gooey		Contact with the Pokémon lowers the attackers Speed stat.	'>Gooey</option>
 <option id='Forewarn		Determines what moves a foe has.	'>Forewarn</option>
 <option id='Wonder Skin		Makes status-changing moves more likely to miss.	'>Wonder Skin</option>
 <option id='suction Cups		Negates all moves that force switching out.	'>Suction Cups</option>
 <option id='simple		Doubles all stat changes.	'>Simple</option>
 <option id='sand Stream		The Pokémon summons a sandstorm in battle.	'>Sand Stream</option>
 <option id='Drought		Turns the sunlight harsh when the Pokémon enters a battle.	'>Drought</option>
 <option id='Cheek Pouch		Restores additional HP when a Berry is consumed.	'>Cheek Pouch</option>
 <option id='Aroma Veil		Protects allies from attacks that limit their move choices.	'>Aroma Veil</option>
 <option id='Zen Mode		Changes form when HP drops below half.	'>Zen Mode</option>
 <option id='White Smoke		Prevents other Pokémon from lowering its stats.	'>White Smoke</option>
 <option id='symbiosis		The Pokémon can pass an item to an ally.	'>Symbiosis</option>
 <option id='stakeout		Deals double damage to Pokémon switching in.	'>Stakeout</option>
 <option id='solid Rock		Reduces damage from super-effective attacks.	'>Solid Rock</option>
 <option id='Protean		Changes the Pokémons type to its last used move.	'>Protean</option>
 <option id='Motor Drive		Raises Speed if hit by an Electric-type move.	'>Motor Drive</option>
 <option id='Long Reach		The Pokémon uses its moves without making contact with the target.	'>Long Reach</option>
 <option id='Liquid Ooze		Damages attackers using any draining move.	'>Liquid Ooze</option>
 <option id='Illusion		Enters battle disguised as the last Pokémon in the party.	'>Illusion</option>
 <option id='Honey Gather		The Pokémon may gather Honey from somewhere.	'>Honey Gather</option>
 <option id='Grassy Surge		The Pokémon creates a Grassy Terrain when it enters a battle.	'>Grassy Surge</option>
 <option id='Forecast		Castform transforms with the weather.	'>Forecast</option>
 <option id='Fluffy		Halves damage from contact moves, but doubles damage from Fire-type moves.	'>Fluffy</option>
 <option id='Flower Veil		Prevents lowering of ally Grass-type Pokémons stats.	'>Flower Veil</option>
 <option id='Download		Adjusts power according to a foes defenses.	'>Download</option>
 <option id='Dancer		Copies the foes Dance moves.	'>Dancer</option>
 <option id='Truant		Pokémon cant attack on consecutive turns.	'>Truant</option>
 <option id='steam Engine		Drastically raises Speed when hit by a Fire- or Water-type move.	'>Steam Engine</option>
 <option id='Ripen		Doubles the effect of berries.	'>Ripen	</option>
 <option id='Refrigerate		Turns Normal-type moves into Ice-type moves.	'>Refrigerate</option>
 <option id='Pure Power		Raises the Pokémons Attack stat.	'>Pure Power</option>
 <option id='Psychic Surge		The Pokémon creates a Psychic Terrain when it enters a battle.	'>Psychic Surge</option>
 <option id='Prism Armor		Reduces damage from super-effective attacks.	'>Prism Armor</option>
 <option id='Power Construct		Changes form when HP drops below half.	'>Power Construct</option>
 <option id='Poison Heal		Restores HP if the Pokémon is poisoned.	'>Poison Heal</option>
 <option id='Pixilate		Turns Normal-type moves into Fairy-type moves.	'>Pixilate</option>
 <option id='Neutralizing Gas		Neutralizes abilities of all Pokémon in battle.	'>Neutralizing Gas</option>
 <option id='Mega Launcher		Boosts the power of aura and pulse moves.	'>Mega Launcher</option>
 <option id='Marvel Scale		Ups Defense if there is a status problem.	'>Marvel Scale</option>
 <option id='Magma Armor		Prevents the Pokémon from becoming frozen.	'>Magma Armor	</option>
 <option id='Liquid Voice		All sound-based moves become Water-type moves.	'>Liquid Voice</option>
 <option id='Libero		Changes the Pokémons type to its last used move.	'>Libero</option>
 <option id='Iron Barbs		Inflicts damage to the Pokémon on contact.	'>Iron Barbs</option>
 <option id='Immunity		Prevents the Pokémon from getting poisoned.	'>Immunity</option>
 <option id='Heatproof		Weakens the power of Fire-type moves.	'>Heatproof</option>
 <option id='Galvanize		Normal-type moves become Electric-type moves and their power boosted.	'>Galvanize	</option>
 <option id='Gale Wings		Gives priority to Flying-type moves.	'>Gale Wings</option>
 <option id='Filter		Reduces damage from super-effective attacks.	'>Filter</option>
 <option id='Drizzle		The Pokémon makes it rain when it enters a battle.	'>Drizzle</option>
 <option id='Arena Trap		Prevents the foe from fleeing.	'>Arena Trap</option>
 <option id='Water Compaction		Sharply raises Defense when hit by a Water-type move.	'>Water Compaction</option>
 <option id='Water Bubble		Halves damage from Fire-type moves, doubles power of Water-type moves used, and prevents burns.	'>Water Bubble</option>
 <option id='Wandering Spirit		Swaps abilities with opponents on contact.	'>Wandering Spirit</option>
 <option id='Unseen Fist		Contact moves can strike through Protect/Detect.	'>Unseen Fist</option>
 <option id='Turboblaze		Moves can be used regardless of Abilities.	'>Turboblaze</option>
 <option id='Teravolt		Moves can be used regardless of Abilities.	'>Teravolt	</option>
 <option id='Tangling Hair		Contact with the Pokémon lowers the attackers Speed stat.	'>Tangling Hair</option>
 <option id='stance Change		Changes form depending on moves used.	'>Stance Change	</option>
 <option id='stamina		Raises Defense when attacked.	'>Stamina</option>
 <option id='shields Down		Changes stats when HP drops below half.	'>Shields Down	</option>
 <option id='screen Cleaner		Nullifies effects of Light Screen, Reflect, and Aurora Veil.	'>Screen Cleaner</option>
 <option id='schooling		Changes Wishiwashi to School Form.	'>Schooling	</option>
 <option id='sand Spit		Creates a sandstorm when hit by an attack.	'>Sand Spit	</option>
 <option id='Punk Rock		Boosts sound-based moves and halves damage from the same moves.	'>Punk Rock	</option>
 <option id='Propeller Tail		Ignores moves and abilities that draw in moves.	'>Propeller Tail</option>
 <option id='Power of Alchemy		The Pokémon copies the Ability of a defeated ally.	'>Power of Alchemy	</option>
 <option id='Pastel Veil		Prevents the Pokémon and its allies from being poisoned.	'>Pastel Veil</option>
 <option id='Normalize		All the Pokémons moves become the Normal type.	'>Normalize</option>
 <option id='Mummy		Contact with this Pokémon spreads this Ability.	'>Mummy</option>
 <option id='Multiscale		Reduces damage when HP is full.	'>Multiscale</option>
 <option id='Misty Surge		The Pokémon creates a Misty Terrain when it enters a battle.	'>Misty Surge</option>
 <option id='Merciless		The Pokémons attacks become critical hits if the target is poisoned.	'>Merciless</option>
 <option id='Intrepid Sword		Boosts Attack in battle.	'>Intrepid Sword</option>
 <option id='Ice Scales		Halves damage from Special moves.	'>Ice Scales</option>
 <option id='Ice Face		Avoids damage from Physical moves for one turn.	'>Ice Face</option>
 <option id='Hunger Switch		Changes forms each turn.	'>Hunger Switch</option>
 <option id='Grass Pelt		Boosts the Defense stat in Grassy Terrain.	'>Grass Pelt</option>
 <option id='Gorilla Tactics		Boosts the Pokémons Attack stat but only allows the use of the first selected move.	'>Gorilla Tactics</option>
 <option id='Fur Coat		Reduces damage from physical moves.	'>Fur Coat</option>
 <option id='Flare Boost		Powers up special attacks when burned.	'>Flare Boost</option>
 <option id='Electric Surge		The Pokémon creates an Electric Terrain when it enters a battle.	'>Electric Surge</option>
 <option id='Defeatist		Lowers stats when HP drops below half.	'>Defeatist</option>
 <option id='Dauntless Shield		Boosts Defense in battle.	'>Dauntless Shield</option>
 <option id='Cotton Down		Lowers foes Speed when hit.	'>Cotton Down</option>
 <option id='Corrosion		The Pokémon can poison Steel and Poison types.	'>Corrosion</option>
 <option id='Berserk		Raises Special Attack when HP drops below half.	'>Berserk</option>
 <option id='Aura Break		Reduces power of Dark- and Fairy-type moves.	'>Aura Break</option>
 <option id='As One		Combines Unnerve and Chilling Neigh/Grim Neigh	'>As One</option>
 <option id='Aerilate		Turns Normal-type moves into Flying-type moves.	'>Aerilate</option>
 <option id='Wonder Guard		Only supereffective moves will hit.	'>Wonder Guard</option>
 <option id='Wimp Out		Switches out when HP drops below half.	'>Wimp Out</option>
 <option id='Victory Star		Boosts the accuracy of its allies and itself.	'>Victory Star</option>
 <option id='Triage		Gives priority to restorative moves.	'>Triage</option>
 <option id='Transistor		Signature ability of Regieleki. Powers up Electric-type moves.	'>Transistor</option>
 <option id='Toxic Boost		Powers up physical attacks when poisoned.	'>Toxic Boost</option>
 <option id='surge Surfer		Doubles Speed during Electric Terrain.	'>Surge Surfer</option>
 <option id='steely Spirit		Powers up ally Pokémons Steel-type moves.	'>Steely Spirit	</option>
 <option id='steelworker		Powers up Steel-type moves.	'>Steelworker</option>
 <option id='stalwart		Ignores moves and abilities that draw in moves.	'>Stalwart</option>
 <option id='stall		The Pokémon moves after all other Pokémon do.	'>Stall</option>
 <option id='soul-Heart		Raises Special Attack when an ally faints.	'>Soul-Heart</option>
 <option id='slow Start		Temporarily halves Attack and Speed.	'>Slow Start		Temporarily halves Attack and Speed.	</option>
 <option id='shadow Shield		Reduces damage when HP is full.	'>Shadow Shield	</option>
 <option id='RKS System		Changes type depending on held item.	'>RKS System</option>
 <option id='Receiver		Inherits an allys ability when it faints.	'>Receiver</option>
 <option id='Quick Draw			'>Quick Draw			</option>
 <option id='Queenly Majesty		Prevents use of priority moves.	'>Queenly Majesty</option>
 <option id='Primordial Sea		Makes it rain heavily when the ability activates.	'>Primordial Sea</option>
 <option id='Power Spot		Just being next to the Pokémon powers up moves.	'>Power Spot</option>
 <option id='Perish Body		When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.	'>Perish Body</option>
 <option id='Parental Bond		Allows the Pokémon to attack twice.	'>Parental Bond</option>
 <option id='Neuroforce		Powers up moves that are super effective.	'>Neuroforce</option>
 <option id='Multitype		Changes type to match the held Plate.	'>Multitype</option>
 <option id='Mirror Armor		Reflects any stat-lowering effects.	'>Mirror Armor</option>
 <option id='Mimicry		Changes type depending on the terrain.	'>Mimicry</option>
 <option id='Innards Out		Deals damage upon fainting.	'>Innards Out</option>
 <option id='Imposter		It transforms itself into the Pokémon it is facing.	'>Imposter</option>
 <option id='Gulp Missile		Returns with a catch in its mouth after using Surf or Dive.	'>Gulp Missile</option>
 <option id='Grim Neigh		Boosts Special Attack after knocking out a Pokémon.	'>Grim Neigh</option>
 <option id='Full Metal Body		Prevents other Pokémon from lowering its stats.	'>Full Metal Body</option>
 <option id='Flower Gift		Powers up party Pokémon when it is sunny.	'>Flower Gift</option>
 <option id='Fairy Aura		Raises power of Fairy type moves for all Pokémon in battle.	'>Fairy Aura</option>
 <option id='Emergency Exit		Switches out when HP falls below 0%.	'>Emergency Exit</option>
 <option id='Dragons Maw		Signature ability of Regidrago. Powers up Dragon-type moves.	'>Dragons Maw</option>
 <option id='Disguise		Avoids damage for one turn.	'>Disguise</option>
 <option id='Desolate Land		Turns the sunlight extremely harsh when the ability activates.	'>Desolate Land</option>
 <option id='Delta Stream		Creates strong winds when the ability activates.	'>Delta Stream</option>
 <option id='Dazzling		Protects the Pokémon from high-priority moves.	'>Dazzling</option>
 <option id='Dark Aura		Raises power of Dark type moves for all Pokémon in battle.	'>Dark Aura</option>
 <option id='Curious Medicine		Resets all stat changes upon entering battlefield.	'>Curious Medicine</option>
 <option id='Comatose		The Pokémon is always asleep but can still attack.	'>Comatose</option>
 <option id='Color Change		Changes the Pokémons type to the foes move.	'>Color Change</option>
 <option id='Chilling Neigh		Boosts Attack after knocking out a Pokémon.	'>Chilling Neigh</option>
 <option id='Battle Bond		Transform into Ash-Greninja after causing opponent to faint.	'>Battle Bond</option>
 <option id='Battery		Raises power of teammates Special moves.	'>Battery</option>
 <option id='Ball Fetch		Retrieves a Poké Ball from a failed throw.	'>Ball Fetch</option>
 <option id='Bad Dreams		Reduces a sleeping foes HP.	'>Bad Dreams</option>

  
 </body></html>
</body>
</html>